CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    email    VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role     VARCHAR(255) CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE vouchers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(255) NOT NULL,
    habitacion       VARCHAR(255) NOT NULL,
    email            VARCHAR(255),
    tipo_comprobante VARCHAR(255) NOT NULL,
    monto            NUMERIC(10, 2) NOT NULL,
    codigo_operacion VARCHAR(20) NOT NULL,
    fecha_pago       DATE NOT NULL,
    celular          VARCHAR(9) NOT NULL,
    archivo_ruta     VARCHAR(255) NOT NULL,
    archivo_nombre   VARCHAR(255),
    archivo_tipo     VARCHAR(255),
    estado           VARCHAR(255) NOT NULL CHECK (estado IN ('PENDIENTE', 'VALIDADO', 'RECHAZADO')),
    fecha_subida     TIMESTAMP(6) NOT NULL
);
