CREATE TABLE habitaciones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100)   NOT NULL UNIQUE,
    esencia     VARCHAR(150)   NOT NULL,
    descripcion VARCHAR(1000)  NOT NULL,
    precio      NUMERIC(10, 2) NOT NULL,
    tamano      INTEGER        NOT NULL,
    capacidad   INTEGER        NOT NULL,
    cama        VARCHAR(100)   NOT NULL,
    vista       VARCHAR(100)   NOT NULL,
    ideal_para  VARCHAR(255)   NOT NULL
);

CREATE TABLE habitacion_amenidades (
    habitacion_id BIGINT       NOT NULL REFERENCES habitaciones (id) ON DELETE CASCADE,
    amenidad      VARCHAR(255) NOT NULL,
    posicion      INTEGER      NOT NULL,
    PRIMARY KEY (habitacion_id, posicion)
);

CREATE TABLE habitacion_condiciones (
    habitacion_id BIGINT       NOT NULL REFERENCES habitaciones (id) ON DELETE CASCADE,
    condicion     VARCHAR(255) NOT NULL,
    posicion      INTEGER      NOT NULL,
    PRIMARY KEY (habitacion_id, posicion)
);

CREATE TABLE habitacion_fotos (
    habitacion_id BIGINT       NOT NULL REFERENCES habitaciones (id) ON DELETE CASCADE,
    src           VARCHAR(255) NOT NULL,
    alt           VARCHAR(255) NOT NULL,
    posicion      INTEGER      NOT NULL,
    PRIMARY KEY (habitacion_id, posicion)
);

CREATE TABLE tratamientos_spa (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icono       VARCHAR(50)    NOT NULL,
    nombre      VARCHAR(100)   NOT NULL UNIQUE,
    descripcion VARCHAR(1000)  NOT NULL,
    duracion    VARCHAR(50)    NOT NULL,
    precio      NUMERIC(10, 2) NOT NULL
);

CREATE TABLE paquetes_spa (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etiqueta    VARCHAR(100)   NOT NULL,
    nombre      VARCHAR(100)   NOT NULL UNIQUE,
    descripcion VARCHAR(1000)  NOT NULL,
    imagen      VARCHAR(255)   NOT NULL,
    duracion    VARCHAR(50)    NOT NULL,
    precio      NUMERIC(10, 2) NOT NULL
);

CREATE TABLE paquete_spa_incluye (
    paquete_id BIGINT       NOT NULL REFERENCES paquetes_spa (id) ON DELETE CASCADE,
    detalle    VARCHAR(255) NOT NULL,
    posicion   INTEGER      NOT NULL,
    PRIMARY KEY (paquete_id, posicion)
);
